name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # TODO: add other os
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - uses: actions/checkout@master

    - name: Install ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy, rustfmt
        override: true
        
    - name: check
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --all --bins --examples

    - name: check no-default-features
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --no-default-features

    - name: tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all
        
    - name: clippy
      uses: actions-rs/clippy-check@v1
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features --tests --examples     
    
    - name: fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

  miri-test-unsafe:
    name: miri-test-unsafe
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: miri
          override: true
      - name: miri
        run: cargo miri test util --no-fail-fast -- --nocapture
        env:
          MIRIFLAGS: -Zmiri-strict-provenance -Zmiri-disable-isolation -Zmiri-symbolic-alignment-check
          PROPTEST_CASES: 10